-
  name: Ansible Playbook python-install.yml
  hosts: [server1]
  tasks:
   - name: Install python and its dependencies.
     apt: name={{ item }} state=present
     with_items:
       - python
       - python-setuptools
       - python-dev
       - build-essential
       - python-pip
       - python3-pip  
       - python-mysqldb
    
   - name: Install python and its dependencies.
     pip: name={{ item }} state=present
     with_items:
       - flask
       - flask-mysql
